# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/22_mavlink.viewsheen_gimbal.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/api/22_mavlink.viewsheen_gimbal.ipynb 7
import time, os, sys

from mavcom.logging import logging
from mavcom.mavlink.mavcom import MAVCom
from mavcom.mavlink.component import BaseComponent, mavutil
# from viewsheen_sdk.gimbal_cntrl import pan_tilt, snapshot,  zoom, VS_IP_ADDRESS, VS_PORT, KeyReleaseThread
from mavcom.camera_sdks.viewsheen.gimbal_cntrl import pan_tilt, snapshot,  zoom, VS_IP_ADDRESS, VS_PORT, KeyReleaseThread

from mavcom.mavlink.vs_gimbal import *

# from mavcom.imports import *   # TODO why is this relative import on nbdev_export?

