# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/99_template.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/api/99_template.ipynb 5
from mavcom.imports import *   # TODO why is this relative import on nbdev_export?
from fastcore.utils import *
import cv2
import gi
import numpy as np
from imutils import resize
# from ping_ip import ping_ip
import threading
from multiprocessing import Process
from gi.repository import Gst
import subprocess
import platform

import paho.mqtt.client as mqtt_client

import time
# from dataloader import LoadImages, resize
from pathlib import Path
import logging
import mavcom.params as params
# gi.require_version('Gst', '1.0')

# %% ../../nbs/api/99_template.ipynb 6
logging.basicConfig(format='%(asctime)-8s,%(msecs)-3d %(levelname)5s [%(filename)10s:%(lineno)3d] %(message)s',
                    datefmt='%H:%M:%S',
                    level=params.LOGGING_LEVEL)  # Todo add this to params
logger = logging.getLogger(params.LOGGING_NAME)
