# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mavcom',
                'doc_host': 'https://johnnewto.github.io',
                'git_url': 'https://github.com/johnnewto/UAV',
                'lib_path': 'tests'},
'syms': {}
  }
